apple_library(
  name = 'Bridging',
  visibility = ['PUBLIC'],
  bridging_header = 'Foo-Bridging-Header.h',
  exported_headers = glob([
    '*.h',
    '**/*.h',
  ]),
  srcs = glob([
    '*.m',
    '**/*.m',
    '*.swift',
    '**/*.swift',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ],
)