apple_test(
  name = 'StringUtilTest',
  info_plist = 'Info.plist',
  info_plist_substitutions = {
    'PRODUCT_BUNDLE_IDENTIFIER': 'com.fkorotkov.StringUtilTest',
  },
  srcs = glob(['*.swift', '*.m']),
  deps = [
  	'//complex_objc_swift:Bridging', # just to have more deps
  	'//simple_mixed_swift_tests/StringUtil:StringUtil',
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
  ],
)